### ISSUE TITLE
Rename Point class to Vector 

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod-robot-simulator#83]
We are using the Point class for 3d Vectors as well. I think the Point name is loaded, Vector is a more generalized term for a set of three numbers

**Comment by guilyx** [comment]
Could do that if you haven't been on it yet. Just renaming the class for every call and definition right ?

**Comment by mithi** [comment]
@guilyx  sure, cool. I'll add you as a contributor in the README afterwards if you like.

**Comment by guilyx** [comment]
Sure, I'll look around other issues as well, namely the quaternions ;)

**Comment by mithi** [comment]
Merged! 🎉🎉
