### ISSUE TITLE
Unused assigned variable (remove this)

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod-robot-simulator#97]
https://github.com/mithi/hexapod-robot-simulator/blob/030cdf7b6b293fc38a04ca8a68ee2527f1f4c8d7/hexapod/ik_solver/recompute_hexapod.py#L43

**Comment by anjolaolubusi** [comment]
Can I take this?

**Comment by mithi** [comment]
Sure! ❤️. It's a stupid mistake I know. 😄
